# Generated by Django 2.2.6 on 2019-11-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='nombre',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
