# Generated by Django 2.2.6 on 2019-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galeria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
