# Generated by Django 2.2.6 on 2019-11-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galeriacuerdas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GaleriaCuerdas',
            new_name='GaleriaCuerda',
        ),
    ]
