# Generated by Django 2.2.6 on 2019-11-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_galeriapercusion_galeriateclado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriacuerda',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='galeriapercusion',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='galeriateclado',
            old_name='image',
            new_name='imagen',
        ),
    ]
