# Generated by Django 2.2.6 on 2019-11-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vision'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vision',
            new_name='Nosotro',
        ),
    ]
