# Generated by Django 2.2.6 on 2019-11-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191112_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mision',
        ),
    ]
