# Generated by Django 2.2.5 on 2019-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_mision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosotro',
            old_name='descripcion',
            new_name='titulo_mision',
        ),
        migrations.RenameField(
            model_name='nosotro',
            old_name='nombre',
            new_name='titulo_pagina',
        ),
        migrations.AddField(
            model_name='nosotro',
            name='descripcion_mision',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotro',
            name='descripcion_vision',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotro',
            name='titulo_vision',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
